services:
  stremio-addon:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "7700:7700"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/manifest.json"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
